# Generated by Django 4.0.3 on 2022-03-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=1024, unique=True)),
                ('author', models.CharField(blank=True, default='', max_length=512)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ChildPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('html_content', models.TextField()),
                ('is_last_page', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('parent_doc_id', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_search.parentdocument')),
            ],
        ),
    ]
