# Generated by Django 4.0.3 on 2024-04-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childpage',
            name='parent_filename',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
